services:
    drupal:
        image: drupal:9
        ports:
            - "8080:80"
        volumes:
            - drupal-modules:/var/www/html/modules
            - drupal-profiles:/var/www/html/profiles
            - drupal-sites:/var/www/html/sites
            - drupal-themes:/var/www/html/themes
        depends_on:
            - mariadb
    mariadb:
        image: mariadb:latest
        environment:
            - MYSQL_ROOT_PASSWORD=mypasswd
            - MYSQL_DATABASE=mydatabase
            - MYSQL_USER=myuser
            - MYSQL_PASSWORD=mypassword

volumes:
    drupal-modules:
    drupal-profiles:
    drupal-sites:
    drupal-themes:


# INSTRUCTION FOR DRUPAL DATABASE SETUP [SETUP DATABASE]
# 1. Database name: mydatabase
#Database user: myuser
#Database password: mypassword
    # Advance setting
        # Database host: mariadb
        # Port : 3306